### PR TITLE
Separate soon-to-be-released features etc.

### PR DESCRIPTION
**Pull request by roesslerj**
(cherry picked from commit acbf11758766bd7057f1d67f4fd47e15dfd97c9a)

### CODE REVIEW

**Review by diba1013 — COMMENTED** [review]
Do we do this with the first beta release or when we actually do the production release?

**Comment by roesslerj** [comment]
Good question—I don't know. I need this on a feature branch (guess which). So I created this as a separate commit and cherry picked it here to reduce the merge conflicts.

**Comment by diba1013** [comment]
@beatngu13 Do we do this with the start or at the end of the release process?

**Comment by beatngu13** [comment]
Usually at the end of the release process on the `release` branch, when we know the final release date and content.

**Comment by roesslerj** [comment]
But please do not change this commit, or else we have merge-hell...

**Comment by beatngu13** [comment]
Then why did you do it in the first place? 🤷‍♂️

**Comment by roesslerj** [comment]
Because I was requested to adapt the changelog for features that are not being released. So I created this commit and cherry-picked it. If you don't change that commit but rather add another one on top of it, all should work out fine.

**Comment by diba1013** [comment]
My thought was to simply not approve the feature branches now at do that once we released. That way the merge hell is on your side (as this is always the case with a changelog)

**Comment by roesslerj** [comment]
Why not just approve this 10 line change and have another one when we need it. We're talking about it way longer than sensible, and not approving it is just creating me unnecessary effort. 🤨

**Comment by beatngu13** [comment]
It is the first time @diba1013 is coordinating an entire release procedure by himself. He asked a legitimate question to see when we usually adapt the changelog. And this PR basically creates unnecessary effort for those that do the actual release. BTW yesterday was a national holiday, today it is weekend, so you shouldn't expect anyone to merge this before Monday. So next time, please think twice before ranting on people's decisions … on 5am on a Saturday.

**Review by beatngu13 — APPROVED** [review]

**Pull request merged**
