### PR TITLE
Experimental cloud persistence

### PR DESCRIPTION
**Pull request by modulo11**
This PR is open for discussion as it contains some rough edges. Please share your general thoughts.

### CODE REVIEW

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by martin-v** [comment]
Looks good for me. But we need a smoother user journey and at least we need to document it.

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by beatngu13** [comment]
Will close until merge conflicts have been resolved.

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Pull request closed without merging**
