### PR TITLE
Fix naming

### PR DESCRIPTION
**Pull request by beatngu13**
See commit message.

### CODE REVIEW

**Comment by roesslerj** [comment]
Hmm. I just yesterday had a conversation with someone for which this doesn't work, as he uses a `CucumberWithSerenity` runner. How would you name that in contrast then?

**Comment by beatngu13** [comment]
Then this is caused by lacking support from our test class and method namer, isn't it? I mean, what the class does is now reflected in the class name: it names suites and tests according to class and method names. This feature supports out-of-the-box several frameworks, currently JUnit and TestNG. Naming it "JUnit-something" and having support for TestNG is more confusing I believe.

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Comment by rebazer** [comment]
Rebase failed, this pull request needs some manual love ...

**Review by roesslerj — APPROVED** [review]

**Pull request merged**
