### PR TITLE
Feature/switch to rhino

### LINKED ISSUE #331: Warning: Nashorn engine is planned to be removed from a future JDK release
I'm using JDK 11, so I assume this should need to be addressing soon.

### PR DESCRIPTION
**Pull request by enesoezel**
There's almost no difference in size regarding the recheck-web jars.
All IT-Test in recheck-web seem to work as before.

resolves #331

### CODE REVIEW

**Comment by diba1013** [comment]
Since you needed to adapt a test, is there any other compatibility problems with rhino? 
1. Does a simple cast to string work?
1. Does the recheck-web ignore.js work?
1. ...

**Comment by enesoezel** [comment]
As I mentioned in the description it seems like recheck-web is working proper. The ignore file works also. Regarding [this stackoverflow post](https://stackoverflow.com/a/26509119), a simple cast does also work like: `String(diff.expected);` or `(diff.expected + "")`. I have tested both. It's working.

**Comment by beatngu13** [comment]
So, too me it looks like this variant is superior to #527. Any objections against merging and testing it during dev and especially when releasing 1.8.0?

**Comment by roesslerj** [comment]
I am also in favor of merging now and testing throughout the sprint.

**Review by roesslerj — APPROVED** [review]

**Review by beatngu13 — APPROVED** [review]

**Pull request merged**
